# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import MySQLdb

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Uss(object):
    def setupUi(self, Uss):
        Uss.setObjectName(_fromUtf8("Uss"))
        Uss.resize(494, 324)
        self.centralwidget = QtGui.QWidget(Uss)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Tab = QtGui.QTabWidget(self.centralwidget)
        self.Tab.setGeometry(QtCore.QRect(0, 10, 621, 411))
        self.Tab.setObjectName(_fromUtf8("Tab"))
        ### Usertab
        self.Usertab = QtGui.QWidget()
        self.Usertab.setObjectName(_fromUtf8("Usertab"))
        self.verticalLayoutWidget = QtGui.QWidget(self.Usertab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 40, 160, 221))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Editar = QtGui.QPushButton(self.verticalLayoutWidget)
        self.Editar.setObjectName(_fromUtf8("Editar"))
        self.verticalLayout.addWidget(self.Editar)
        self.Eliminar_2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.Eliminar_2.setObjectName(_fromUtf8("Eliminar_2"))
        self.verticalLayout.addWidget(self.Eliminar_2)
        self.gridLayoutWidget = QtGui.QWidget(self.Usertab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 231, 231))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lineEdit_5 = QtGui.QTextEdit(self.gridLayoutWidget)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.verticalLayout_3.addWidget(self.lineEdit_5)
        self.lineEdit_4 = QtGui.QTextEdit(self.gridLayoutWidget)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.verticalLayout_3.addWidget(self.lineEdit_4)
        self.lineEdit_3 = QtGui.QTextEdit(self.gridLayoutWidget)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.lineEdit_2 = QtGui.QTextEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.lineEdit = QtGui.QTextEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.paisl = QtGui.QLabel(self.gridLayoutWidget)
        self.paisl.setObjectName(_fromUtf8("paisl"))
        self.verticalLayout_2.addWidget(self.paisl)
        self.telf = QtGui.QLabel(self.gridLayoutWidget)
        self.telf.setObjectName(_fromUtf8("telf"))
        self.verticalLayout_2.addWidget(self.telf)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.Usertab)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 171, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.Tab.addTab(self.Usertab, _fromUtf8(""))
        ###Carrito
        self.Cartab = QtGui.QWidget()
        self.Cartab.setObjectName(_fromUtf8("Cartab"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.Cartab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(320, 20, 151, 231))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lineEdit3 = QtGui.QTextEdit(self.verticalLayoutWidget_4)
        self.lineEdit3.setObjectName(_fromUtf8("lineEdit3"))
        self.Eliminar = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.Eliminar.setObjectName(_fromUtf8("Eliminar"))
        self.verticalLayout_4.addWidget(self.Eliminar)
        self.compart = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.compart.setObjectName(_fromUtf8("compart"))
        self.verticalLayout_4.addWidget(self.compart)
        self.carritotable = QtGui.QTableView(self.Cartab)
        self.carritotable.setGeometry(QtCore.QRect(10, 10, 291, 261))
        self.carritotable.setObjectName(_fromUtf8("carritotable"))
        self.Tab.addTab(self.Cartab, _fromUtf8(""))
        ####artv
        self.ArtTab = QtGui.QWidget()
        self.ArtTab.setObjectName(_fromUtf8("ArtTab"))
        self.artobtable = QtGui.QTableView(self.ArtTab)
        self.artobtable.setGeometry(QtCore.QRect(20, 20, 451, 241))
        self.artobtable.setObjectName(_fromUtf8("artobtable"))
        self.Tab.addTab(self.ArtTab, _fromUtf8(""))
        self.TTab = QtGui.QWidget()
        self.TTab.setObjectName(_fromUtf8("TTab"))
        self.label_5 = QtGui.QLabel(self.TTab)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox = QtGui.QTextEdit(self.TTab)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 111, 27))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.TTab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(220, 0, 141, 62))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.Comprar = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.Comprar.setObjectName(_fromUtf8("Comprar"))
        self.verticalLayout_5.addWidget(self.Comprar)
        self.Agregar = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.Agregar.setObjectName(_fromUtf8("Agregar"))
        self.verticalLayout_5.addWidget(self.Agregar)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.TTab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(370, 0, 111, 61))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_6.addWidget(self.label_6)
        self.lineEdit_6 = QtGui.QTextEdit(self.verticalLayoutWidget_3)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.verticalLayout_6.addWidget(self.lineEdit_6)
        self.buscar = QtGui.QPushButton(self.TTab)
        self.buscar.setGeometry(QtCore.QRect(130, 30, 71, 27))
        self.buscar.setObjectName(_fromUtf8("buscar"))
        self.tiendatable = QtGui.QTableView(self.TTab)
        self.tiendatable.setGeometry(QtCore.QRect(20, 70, 451, 192))
        self.tiendatable.setObjectName(_fromUtf8("tiendatable"))
        self.Tab.addTab(self.TTab, _fromUtf8(""))

        self.retranslateUi(Uss)
        self.Tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Uss)

    def retranslateUi(self, Uss):
        Uss.setWindowTitle(_translate("Uss", "User room", None))
        self.Editar.setText(_translate("Uss", "Editar informacion", None))
        self.Eliminar_2.setText(_translate("Uss", "Guardar", None))
        self.label_2.setText(_translate("Uss", "ID:", None))
        self.label.setText(_translate("Uss", "Nombre:", None))
        self.label_4.setText(_translate("Uss", "Correo:", None))
        self.paisl.setText(_translate("Uss", "Pais:", None))
        self.telf.setText(_translate("Uss", "Telefono", None))
        self.label_3.setText(_translate("Uss", "Informacion del Usuario", None))
        self.Tab.setTabText(self.Tab.indexOf(self.Usertab), _translate("Uss", "Usuario", None))
        self.Eliminar.setText(_translate("Uss", "Eliminar del carrito", None))
        self.compart.setText(_translate("Uss", "Comprar Articulo", None))
        self.Tab.setTabText(self.Tab.indexOf(self.Cartab), _translate("Uss", "Carrito", None))
        self.Tab.setTabText(self.Tab.indexOf(self.ArtTab), _translate("Uss", "Articulos Obtenidos", None))
        self.label_5.setText(_translate("Uss", "Categorias", None))
        self.Comprar.setText(_translate("Uss", "Comprar", None))
        self.Agregar.setText(_translate("Uss", "Agregar a carrito", None))
        self.label_6.setText(_translate("Uss", "Cantidad", None))
        self.buscar.setText(_translate("Uss", "Buscar", None))
        self.Tab.setTabText(self.Tab.indexOf(self.TTab), _translate("Uss", "Tienda", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Uss = QtGui.QMainWindow()
    ui = Ui_Uss()
    ui.setupUi(Uss)
    Uss.show()
    sys.exit(app.exec_())

